# Written for Mac OSX - 10.7.4

chap3: main.cpp vanilla_option.o
	clang++ -o chap3 main.cpp vanilla_option.o -arch x86_64

vanilla_option.o: vanilla_option.cpp
	clang++ -c vanilla_option.cpp -arch x86_64
